### ISSUE TITLE
GET /act_feature/:id 好像少了 'scale'

### ISSUE THREAD

**Issue by wesley100002001** [watchout-tw/core#66] opened 2017-07-19 10:59 UTC
{
    "statusCode": 200,
    "object": {
        "id": 1,
        "specific_topic": {
            "id": 1,
            "image": null,
            "index": 1,
            "title": "罷免"
        },
        "act": {
            "id": 1,
            "title": "公職人員選舉罷免法",
            "official_seq_no": "1044"
        },
        "act_dir": {
            "id": 1,
            "name": "降低罷免門檻"
        },
        "feature": "提案門檻",
        "dir": "降低提案門檻"
    }
}
這是現在的 response

**Comment by chihaoyo** [comment] 2017-07-20 00:19
This is a duplicate of #60.

**Closed by chihaoyo** 2017-07-20 00:19 UTC
Labels: medium

**Comment by chihaoyo** [comment] 2017-07-20 00:21
Also, please use Markdown‘s code block (start and end with ```) so code inside issue is readable. @wesley100002001 @charlieworld
